### ISSUE TITLE
getting shrine-tus to run in a rails application

### ISSUE THREAD

**Issue by ivanamihalek** [janko-m/shrine-tus#2]
Dear @janko-m 

Thank you for keeping this code open. I  have integrated [shrine](https://github.com/janko-m/shrine) with a Rails application, and it was a breeze, thanks. No such luck with shrine-tus. In particular it looks like I have trouble understanding the tus-server end. Would it be possible to get some more help?

I tired shrine-tus-demo, and it is not quite working for me either, but I would not pursue that much further, since it is not quite RoR anyway.  I can see, however, that you have something called TusApp which is [not mentioned anyplace else in tne code](https://github.com/janko-m/shrine-tus-demo/search?utf8=%E2%9C%93&q=TusApp&type=). How is TusApp supposed to work? 

I can also see that in [tus-ruby-server](https://github.com/janko-m/tus-ruby-server) you are suggesting defining the endpoint location in config,ru. What should be the equivalent for TusApp? Where should /files directory be on the server? Would it be a bad idea to make it point to public/uploads/cache in the app? 

Any help would be very much welcome.

**Comment by janko-m** [comment]
I updated the [shrine-tus-demo README](https://github.com/janko-m/shrine-tus-demo#shrine-tus-demo) with a thorough explanation of the demo implementation, along with some instructions for alternative implementations. Let me know if that helps you integrate `shrine-tus`!

**Comment by janko-m** [comment]
To also answer your questions inline:

> I can see, however, that you have something called TusApp which is not mentioned anyplace else in tne code. How is TusApp supposed to work?

TusApp is a standalone app that's running on its own port (`localhost:9000` in the demo), separately from the main application. The reason why the `TusApp` constant is not referenced anywhere else is because only `tus-js-client` (JavaScript) communicates with that application through `localhost:9000`.

> I can also see that in tus-ruby-server you are suggesting defining the endpoint location in config,ru. What should be the equivalent for TusApp?

These are the two different approaches: either use a separate application preferably running on Goliath (this is what the demo uses), or run the tus server as a Rack app alongside your main app. The `tus-ruby-server` README explains both approaches.

> Where should /files directory be on the server?

The `/files` is not a directory, it's an endpoint prefix. If you use the approach of running the tus server alongside your app, then you need to specify a "mount point", and `/files` was just an example of a mount point.

> Would it be a bad idea to make it point to public/uploads/cache in the app?

It wouldn't be a bad idea, but it probably doesn't make much sense, as the files uploaded to the tus server won't be served by your Rails app but by the `tus-ruby-server`, which can serve files from any directory. But I don't see any harm in saving those files to ` public/uploads/cache` if you prefer it that way.

**Comment by ivanamihalek** [comment]
OK thank you for the detailed answer. I'll give ti a shot and close the thread for now.
